### ISSUE TITLE
Remove packet_index_reset parameter from protocol

### ISSUE THREAD

**Issue by truvorskameikin** [truvorskameikin/udp-discovery-cpp#1]
It is not good to reset packet index while discovery application is running. Packet index reset is sent in single UDP packet that can be lost and other peers will not get it and will keep old and large value of packet index. So the solution is to store packet index in 64 bit integer. Even if the peer will send packet every second it can run without overflow of packet index almost forever.

**Comment by zapek** [comment]
Ouch! This is not backward compatible.
